version: '3.6'
services:
  compute:
    image: "helm-valip-quay-quay-quay.apps.vapo-aws-dsoi-dev.va.gov/helm/helm-valip-iris-compute:1.0.14-3d908a2"
    command: --check-caps false --key /ICS/iris.key
    restart: always
    ports:
      - 2188
      - 19800:1972
      - 57700:52773
      - 53773
    volumes:
      - /efs/ICS:/ICS
